services:
  front:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app  
    
  back:
    build: 
      context: back
      dockerfile: Dockerfile
    ports:
      - 5174:5174
    volumes:
      - ./back:/usr/src/app
    tty: true
    